apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: vivacious-line
  name: vivacious-line-database
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: placeholder-app-label-d46881878f594a2dadfd963843452aab
    deploymentconfig: vivacious-line-database
  sessionAffinity: None
  type: ClusterIP
