apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
  labels:
    app: vivacious-line
    app.kubernetes.io/part-of: fruitstocker
    app.kubernetes.io/name: mysql-database
    app.kubernetes.io/instance: vivacious-line-database 
  name: vivacious-line-database
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: placeholder-app-label-d46881878f594a2dadfd963843452aab
    deploymentconfig: vivacious-line-database
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: vivacious-line-database
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: verysecretrootpassword
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: vivacious-line-database-db-bind
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: vivacious-line-database-db-bind
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: vivacious-line-database-db-bind
        image: image-registry.openshift-image-registry.svc:5000/openshift/mysql@sha256:16386423eaa147384d3a9820f3eb47aa1e7b93570f4d577593931d1f0cf09176
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        name: vivacious-line-database
        ports:
        - containerPort: 3306
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
              -e 'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - vivacious-line-database
      from:
        kind: ImageStreamTag
        name: mysql:5.7
        namespace: openshift
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/openshift/mysql@sha256:16386423eaa147384d3a9820f3eb47aa1e7b93570f4d577593931d1f0cf09176
    type: ImageChange
