apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  annotations:
  name: todo-serverless
  namespace: gartner3
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/catalyst1/todo
        name: user-container
        ports:
        - containerPort: 3000
